POST http://localhost:8080/api/v1/image
Content-Type: application/json

{
    "image": "i am here"
}

###
POST http://localhost:8080/api/v1/image/vectorize
Content-Type: application/json

{
    "text": "i am software engineer"
}


POST http://localhost:8080/api/v1/image
Content-Type: application/json

{
    "image": "i am here"
}
### vectproze chcks
POST http://localhost:8080/api/v1/search/vectorize-text
Content-Type: application/json

{
  "text": "black cat"
}
